### ISSUE TITLE
What exactly are the rules for `UnsafeCell::get_mut`?

### ISSUE THREAD

**Issue by CAD97** [rust-lang/unsafe-code-guidelines#333] opened 2022-04-30 13:02 UTC
Miri is somewhat inconsistent here:

```rust
use std::cell::UnsafeCell;

fn main() {
    let mut cell = UnsafeCell::new(0);
    let ptr = cell.get();
    unsafe { *ptr += 1; }

    // 3 alternatives:

    *cell.get_mut() += 1; // miri doesn't complain
    // *(&mut cell).get_mut() += 1; // miri complains
    // *UnsafeCell::get_mut(&mut cell) += 1; // miri complains

    unsafe { *ptr += 1; }

    dbg!(cell.get_mut());
}
```

(origininally discovered by @steffahn [on urlo](https://users.rust-lang.org/t/cursed-pinned-cells/74928/5?u=cad97))

**Comment by RalfJung** [comment] 2022-04-30 16:19
This is another 2-phase reference weirdness -- `cell.get_mut()` creates a two-phase reference which has `SharedReadWrite` permission and thus joins the equivalence class that `ptr` is already in. Hence both of these pointers can be used interchangeably.

Whether that is what we want to happen I am not sure. ;)

**Comment by RalfJung** [comment] 2022-06-27 21:04
So, closing as duplicate of https://github.com/rust-lang/unsafe-code-guidelines/issues/85.

**Closed by RalfJung** 2022-06-27 21:04 UTC
