### ISSUE TITLE
link to current version of book is broken.

### ISSUE THREAD

**Issue by nakshay** [rust-lang/unsafe-code-guidelines#103] opened 2019-03-16 16:16 UTC
link in readme.md is broken ()
https://rust-rfcs.github.io/unsafe-code-guidelines/book

**Comment by gnzlbg** [comment] 2019-03-16 16:18
Duplicate of #1 - this is blocked on adding a `GITHUB_TOKEN` for the repo.

**Closed by gnzlbg** 2019-03-16 16:18 UTC
