### ISSUE TITLE
Confused about IO safety

### ISSUE THREAD

**Issue by TOETOE55** [rust-lang/unsafe-code-guidelines#428] opened 2023-07-08 06:47 UTC
AFAIK, safe rust just only  guarantees something under the control of the Rust compiler (i.e. rust primitive operations) is sound while external operations like FFI or any other OS features are not guaranteed. For example, to read and write [`proc/self/mem`](https://doc.rust-lang.org/stable/std/os/unix/io/index.html#procselfmem-and-similar-os-features) is safe in rust but it's not actually safe though we have obeyed the safety rules of the fs API. (The safety rules are incomplete.)

I'm confused about IO safety after reading the [RFC 3128](https://rust-lang.github.io/rfcs/3128-io-safety.html). What does IO safety actually guaranteed? How does IO safety do it? Why is this sound? And does `proc/self/mem` violate IO safety?

Thanks.

**Comment by RalfJung** [comment] 2023-07-08 07:49
Rust library types can define their own invariants. E.g. you can define a type `struct Even(i32)` and ensure that it can only ever be constructed for even integers. Then soundness for your particular type is about "being even", even though that is not a concept that the Rust language itself knows about.

The same happens with IO safety: the Rust standard library is using Rust features such as private fields and type invariants to guarantee properties about IO performed through these types/traits. As long as types like `OwnedFd` are used according to their specs and docs, and programs don't do their own IO bypassing those types (which they are not supposed to do), there is a guarantee that if you own an FD nobody else will mess with it.

**Comment by TOETOE55** [comment] 2023-07-08 08:23
Let me take a moment to understand this. IO safety is actually more like a kind of invariant at the "library level",  guaranteeing that user or third-party libraries cannot break some internal properties of "owned IO" library.

It seems that It's not  the "safety" in usual sense(e.g. dereferring a raw pointer).

**Comment by Lokathor** [comment] 2023-07-08 18:34
It's safety in the `&str` sense: The bytes must be valid utf8 bytes and if that's not the case it's the fault of whoever messed up the bytes, not the person who read the bad bytes and then did an OOB read (or whatever else wrong thing happened)

**Comment by RalfJung** [comment] 2023-07-09 14:04
@TOETOE55 you are right that there are basically two levels of safety -- the one hard-coded in the language and understood by the compiler (sometimes called "validity"), and the one expressed as a user-level concept with a type's private invariants.  [This blog post](https://www.ralfj.de/blog/2018/08/22/two-kinds-of-invariants.html) explains that in some more detail.

IO-safety is of the second, user-defined kind.

**Comment by TOETOE55** [comment] 2023-07-10 11:59
@RalfJung Thanks! Maybe I got it. 

> the one hard-coded in the language and understood by the compiler (sometimes called "validity")

But I still want to confirm whether this case includes FFI(or other external symbols) calls, and whether rust-lang (will) only guarantee the soundness of language-primitive (excluding of FFI calls)?

**Comment by CAD97** [comment] 2023-07-11 06:41
Rust (the language) doesn't strictly _guarantee_ anything, because it gives you (the programmer) the power to violate those guarantees with `unsafe`. Safe Rust (the language subset) does strictly guarantee language-level validity, so long as all `unsafe` is soundly encapsulated. Safe Rust APIs are considered "sound" if they uphold the guarantees of validity even when actively misused.

What the UCG calls "validity" are the rules that your `unsafe` MUST obey, on immediate pain of **UB** if you violate them. These are the primitive guarantees such as byte/layout validity, but the borrow/memory model also classes as a validity requirement. There are also some validity requirements which are highly impractical to violate from user code and are more requirements placed on the host implementation (e.g. that control flow is predictably structured), but anything is theoretically possible when programming the host directly with `asm!`.

What the UCG calls "safety" is any encapsulation guarantees established by the code in order to provide the soundness guarantee. Violating safety does not necessarily immediately result in "language UB" — what your code does is still consistently defined — but does give the violated library "permission" to arbitrarily violate validity either immediately or whenever in the future. This is colloquially called "library UB;" while some given API usage may not cause language-level UB with _these exact library versions_, a different, compatible library version may result in upgrading library-level UB to language-level UB.

Remember that **UB** means that the behavior of your code is fully (and retroactively) unpredictable. Possible results can only be very roughly bounded by what the machine is actually capable of doing, and debuggers may confidently provide inaccurate information, but the most insidious result is that everything works the way you would expect it to (for now). In this way, there's not that much of a difference between "language UB" and "library UB" if you don't control the library.

`unsafe` code walks the thin line of being able to violate _safety_, and thus the burden of proving _soundness_ being on the developer. With strong guarantees from the library, you can temporarily suspend _safety_ and e.g. put non-UTF-8 bytes into a `String`'s backing buffer, so long as you can guarantee that the bytes are valid UTF-8 again before invoking any code which might potentially rely on that safety requirement. Controlling the library is the strongest guarantee, as you can rely on the exact implementation, rather than needing documented API guarantees to be able to play looser with safety.

FFI is indeed an interesting case. Rust (the language) knows nothing about FFI, and as such, it is fundamentally `unsafe` to perform. In the most strictest sense, calling FFI incorrectly is always[^1] a _safety_ requirement, because there's no **UB** caused by evaluation of Rust code; any **UB** is a result of something which was done on the other side of the FFI bridge. Rust (the language) provides absolutely zero guarantees about the behavior of FFI, and maintaining safety/validity is entirely on the programmer.

[^1]: Minor nitpick: that the function ABIs are compatible is a _validity_ requirement when the call happens. You can argue that this is a _validity_ requirement imposed by the FFI receiver, though, which leaves getting the call correct as technically only a _safety_ requirement. Just one immediately relied upon for validity.

But there are things exposed by std which are implemented with FFI, and for essentially everyone except T-lang, T-libs, or subteams thereof, `std` is essentially part of "the Rust language." If a `std` API is safe to call (and no `unsafe` has been used to violate any safety preconditions), then `std` is providing a guarantee that anything done by the API call is sound. The ability to write to `/proc/mem/self` is one of a very few minor exceptions, and a concession to being practical over being perfect. A "moral high ground" position would say that a system which allows a `/proc/mem/self` to be writable is a "non-conformant" host for the Rust std; the more diplomatic is to say that some host capabilities go around the Rust safety model.

To reiterate, soundness of FFI is a soundness guarantee provided by the standard library. Validity is required by the language independent of the library. Since you don't control the library, the only effective differences are that:

- Miri can be used to detect validity problems in pure-Rust code plus a decent portion of host-interacting std, but not soundness problems; and
- Specific library APIs might document careful relaxations in safety requirements when combined with `unsafe`.

**Comment by RalfJung** [comment] 2023-07-26 13:21
Closing this issue as I hope the question has been answered.

**Closed by RalfJung** 2023-07-26 13:21 UTC

**Comment by TOETOE55** [comment] 2023-08-21 06:29
I thought, I already understood, so I wrote an article https://rustmagazine.org/issue-4/a-brief-discussion-on-invariants-in-rust/
