### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang/unsafe-code-guidelines#52] opened 2018-11-29 17:25 UTC
Do we need to discuss C's provenance model?

**Comment by asajeffrey** [comment] 2018-11-29 17:52
@RalfJung do raw pointers carry provenance, or just references? (So, is ref-to-raw-ptr-to-ref a no-op, or is raw-ptr-to-int-to-raw-ptr?)

**Comment by rkruppe** [comment] 2018-11-29 17:52
> We'd also probably sacrifice a lot of performance, though unfortunately I know of no analysis that shows how much performance which of C's restrictions on pointers actually gains.

It is always difficult to fairly to evaluate how much optimization power a given UB actually enables and which concrete instances of optimizations could be salvage in specific circumstances by a different (often more involved) analysis, especially when you put no upper bound on the amount of engineering you're willing to invest into that. However, this particular UB is so fundamental to alias analysis of C-like languages that I have very little hope of ever encountering a real world optimizer that doesn't have this assumption (or an even stronger one, if it doesn't support C in the first place) hard-coded. Even when there's some escape hatch, optimizations will not be built to handle it as gracefully as possible, so even independent of LLVM, trying to allow cute little programs like this will effectively kneecap any optimizers.

So there needs to be really, *really*, **really** good rationale for allowing this sort of shenanigans. By my current knowledge, even allowing reading of uninitalized variables has better justification (in that there's at least a genuinely-novel and potentially-useful data structure that relies on it).

**Comment by RalfJung** [comment] 2018-11-29 20:55
@asajeffrey That's a hard question. Raw pointers certainly carry *some* provenance about which allocation they point to, i.e., your example is UB even with raw pointers. Beyond that, Stacked Borrows currently does not assign them any provenance, but that is [known to not match LLVM's noalias](https://rust-lang.zulipchat.com/#narrow/stream/136281-wg-unsafe-code-guidelines/topic/stacked.20borrows.3A.20llvm-noalias.20violation.20in.20safe.20code). The path forward here is not clear yet.

**Comment by asajeffrey** [comment] 2018-11-29 22:58
Is there a way to use the stacked borrows model to make pointers just integers by keeping the provenance information in the memory rather than the pointer value, then on converting a `*T` to a `&T` checking that there is an appropriate borrow, and that the `T` value being pointed to all has the same provenance? This would deal with the example from the blog post:
```rust
  let mut x = false;
  let mut y = false;
  if (&x as usize + 1) == (&y as usize) {
    let z: *mut bool = (&mut x as *mut bool as usize + 1) as *mut bool;
    let z: &mut bool = unsafe { &mut *z };
    *z = true;
  }
  y // can be optimized to false
```
since there's an implicit freezing of `y`, so the unsafe block is UB since there is no "appropriate" borrow of `&mut y`.

Er, lots of hand-waving there about what an "appropriate" borrow is.

**Comment by RalfJung** [comment] 2018-11-30 08:53
Stacked Borrows inherently makes it so that two pointers to the same location are *not* equivalent to use:
```rust
let x = &mut 0;
let y = &mut *(x as *mut _);
*y = 4; // allowed
*x = 2; // allowed, but invalidates y
*y = 1; // NOT ALLOWED
```
A model without provenance inherently cannot distinguish `x` and `y`. Thus, I think the fundamental goal of Stacked Borrows to be a dynamic version of the borrow checker cannot be achieved without provenance.

**Comment by asajeffrey** [comment] 2018-11-30 14:47
Hmm, so values of type `&T` have to carry some metadata about lifetimes, Do they need provenance as well though? Could we have a model where `usize` and `*T` are just bitstrings, and `&T` contains additional lifetime metadata?

**Comment by asajeffrey** [comment] 2018-11-30 14:53
A variant example:
```rust
  let mut p = (false, false);
  let x = &mut p.0;
  let z = (&x as *mut bool as usize + 1) as *mut bool;
  let z = unsafe { &mut *z };
  *z = true;
  &p.1; // can be optimized to false???
```
I think this optimization is allowed, because I think this program is UB.

**Comment by RalfJung** [comment] 2018-11-30 14:55
I don't understand the distinction between provenance and "lifetime metadata". Also, people `transmute` between references, pointers and `usize` and expect that to work.

What happens, basically, is that we have two kinds of values: bitstrings, and pointers. Pointers carry provenance, meaning there are pointers that "point to the same thing" and yet are different. This is part of the abstract machine on which Rust runs and completely independent of any type system. We can then ask which effects various operations such as casting and loading from/storing to memory can have on each of these values. This is a long and complicated discussion that [you can write entire papers about](http://www.mpi-sws.org/~jung/twinsem/twinsem.pdf) and still be far from done.

In Stacked Borrows, I am trying to restrict provenance in raw pointers to a minimum. For example, casting ref-to-raw will "strip" the tag that Stacked Borrows uses to identify where a reference comes from. (However, it will still track which allocation the pointer points to. I see no possibility of allowing cross-allocation reasoning even for raw pointers. I also see very little motivation for that.) However, you can still transmute a reference to a raw pointer and then use that, and we have to say what happens (and people [don't like it](https://internals.rust-lang.org/t/stacked-borrows-an-aliasing-model-for-rust/8153/10) when we make that UB).

**Comment by RalfJung** [comment] 2018-11-30 14:57
> I think this optimization is allowed, because I think this program is UB.

I agree, [and so does miri](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=698aeb5db33187d305680a159d68fdbe) (select "Tools - Miri" to see it report this as UB).

**Comment by Gankro** [comment] 2019-02-04 02:06
Not 100% sure if this is the right issue, but wanted to toss this out here:

[Cheri reported compatibility issues related to provenance when porting C software to its platform](https://www.cl.cam.ac.uk/research/security/ctsrd/pdfs/201904-asplos-cheriabi.pdf). (See section 5.3)

We have largely ignored Cheri in the design of the rust platform on the assumption that it's vaporware, but it seems that [ARM has just announced that they are implementing native CHERI support](https://www.theregister.co.uk/AMP/2019/01/28/ukgov_secure_by_design_70m_arm_cambridge/?__twitter_impression=true).

Note also that Cheri requires size_t and intptr_t be different (as discussed in the paper), as intptr_t is 128-bit and size_t is still 64-bit (iiuc). Also intptr_t needs to be codegen'd as if it is a pointer in order to maintain the hardware-level integrity of the tag bits it stores.

**Comment by RalfJung** [comment] 2019-08-14 07:43
FWIW, the glossary now contains a [definition of provenance](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#pointer-provenance).

**Comment by jrtc27** [comment] 2021-03-10 23:18
> @gankro
> 
> I suspect that if ARM does add CHERI support, they will do it without changing the size of a pointer, instead using something similar to their [memory tagging extension](https://community.arm.com/processors/b/blog/posts/arm-a-profile-architecture-2018-developments-armv85a) which uses the top 8 bits of a pointer that are ignored by the hardware.

That is not, and never can be CHERI. 8 bits is nowhere near enough to encode all of:

* fine-grained bounds
* fine-grained permissions
* sealing, a form of opaque reference for constrained domain transitions, critical for interaction between compartments

CHERI is always going to be using capabilities that are two times the native word size (there was an uncompressed 256-bit version originally, but that is clearly not practical). Fitting everything into 128 bits is already a significant technical accomplishment. Plus MTE potentially has other uses in a world with CHERI in order to accelerate temporal safety schemes.

**Comment by nico-abram** [comment] 2021-08-10 19:54
I found a C WG14 draft [N2676](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2676.pdf) that discusses provenance (And [N2624 "Introduction for discussion of N2577"](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2624.pdf) (N2577 is N2676 without a small patch) ). I'm sharing it here since it seems relevant/interesting prior art. At one point, to support these desireable behaviours:
![imagen](https://user-images.githubusercontent.com/24706838/128925736-665e066e-d3bf-4136-b619-4629cfdbde0a.png)
It defines some possible models:
![imagen](https://user-images.githubusercontent.com/24706838/128925763-7e8c322f-ba69-4c8b-be7c-aa4d21e6091e.png)

Is the "copying pointer values with memcpy" usecase similar/equivalent to transmuting pointers/references?

**Comment by jrtc27** [comment] 2021-08-10 20:03
A couple of notes:

1. In CHERI C, much of that becomes unnecessary; `intptr_t` is still a real capability type, not a plain integer (though we let you manipulate it as if it were one, with certain constraints if it is an actual valid capability). The need for some of the changes to C stem from `intptr_t` being typedef'ed to a plain integer type so you have much weaker guarantees about what software could be doing with them, whereas in our model the provenance is tracked in the hardware and maintained throughout and we know that any cast to a plain integer type will not result in a valid pointer when cast back. This does render several of the examples broken by design, but supporting them would require a lot of complexity for code that should not exist (e.g. if you printf then scanf a pointer you will just get back the integer address and be unable to dereference it).
2. The "copying pointer values with memcpy" is not related; that is just to say that:
```
struct foo {
    void *p;
};
void copy_foos(struct foo *dst, const struct foo *src, size_t n) {
    memcpy(dst, src, n * sizeof(struct foo));
}
```
had better work and behave as if you had assigned rather than memcpy'd (see also the realloc example, which is basically the same thing, except that the memcpy is an implicit part of the realloc interface when it has to move your allocation).

**Comment by CAD97** [comment] 2022-03-20 09:30
I have no idea where to properly note this, but I wanted to note it down:

There's [at least some desire](https://www.reddit.com/r/rust/comments/ti6uvg/rusts_unsafe_pointer_types_need_an_overhaul/i1doglh?utm_medium=android_app&utm_source=share&context=3) for _`f64`_ to be able to hold provenance information, so that NaN-boxing can potentially be seen through by the optimizer.

Personally, my opinion is just "yikes." By this time I'm firmly on the side that traditional ptrtoint needs to leak provenance such that act of god divining the address elsewhere in the process is valid. (But hopefully there's a way for the compiler to ptrtoint without leaking provenance, so you can e.g. display an address without considering the provenance leaked.)

**Comment by thomcc** [comment] 2022-03-24 00:55
You can implement Nanboxing using a `NonNull<()>` on 64 bit. On 32 bit you'd need the union approach. This is true for most nanboxing schemes (and I've never seen one that actually passed f64 around, they almost always either use an integer (possibly wrapped in a struct), or a union).

This is one of the cases I'm thinking of when I've commented that ptr->int is often used to avoid duplicate code though.

**Comment by JakobDegen** [comment] 2023-06-06 16:43
Closing, provenance exists and the questions here are answered

**Closed by JakobDegen** 2023-06-06 16:43 UTC
Labels: C-discussion-topic, A-provenance
